const app=document.querySelector('#app'),cats=['ALL','OUTER','TOP','PANTS','SKIRT','OPS','ACC'];
const money=n=>'₩'+n.toLocaleString('ko-KR'),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={OUTER:['Structured jacket','Relaxed trench coat','Minimal zip jacket','Wool short coat'],TOP:['Essential cotton tee','Fine knit pullover','Oversized poplin shirt','Ribbed sleeveless'],PANTS:['Wide pleated trousers','Straight denim','Cotton easy pants','Tailored slacks'],SKIRT:['Long column skirt','Pleated midi skirt','Denim skirt','Wrap skirt'],OPS:['Minimal slip dress','Cotton shirt dress','Layered knit dress','Sleeveless long dress'],ACC:['Everyday tote','Canvas shoulder bag','Leather belt','Soft knit scarf']};
const products=Object.keys(names).flatMap((cat,ci)=>Array.from({length:100},(_,i)=>({id:ci*100+i+1,cat,name:names[cat][i%4]+(i>=4?' / '+String(Math.floor(i/4)+1).padStart(2,'0'):''),price:cat==='OUTER'?129000+(i%4)*10000:cat==='ACC'?29000+(i%4)*10000:49000+(i%4)*15000,img:'assets/'+cat.toLowerCase()+'-'+i%4+'.svg'})));
let cart=[],profile=null,posts=[],orders=[];
try{const s=JSON.parse(localStorage.getItem('doa-demo')||'null');if(s){cart=s.cart||[];profile=s.profile||null;posts=s.posts||[];orders=s.orders||[]}}catch{}
if(!posts.length)posts=[{id:1,title:'나만의 속도로, 도시의 오후',author:'DOA EDITOR',text:'익숙한 거리에서도 새로운 취향을 만나요. 여유 있는 실루엣과 차분한 레이어링.',image:'assets/outer-0.svg',tags:[1,201],likes:24,comments:[]},{id:2,title:'Less, but personal.',author:'MIN',text:'담백한 셔츠와 데님. 매일 손이 가는 나의 조합.',image:'assets/top-2.svg',tags:[103,202],likes:18,comments:[]},{id:3,title:'오늘의 작은 발견',author:'JIWOO',text:'계절 사이, 가벼운 니트 하나로 완성한 아웃핏.',image:'assets/top-1.svg',tags:[102,501],likes:12,comments:[]}];
let logged=false,searchQuery='',communitySort='latest';
const save=()=>{try{localStorage.setItem('doa-demo',JSON.stringify({cart,profile,posts,orders}))}catch{toast(t("브라우저 저장 공간이 부족합니다. 현재 화면에서만 유지됩니다."))}updateHeader()};
function toast(t){const el=document.querySelector('#toast');el.textContent=t;el.style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.style.display='none',3000)}
function updateHeader(){translateShell();document.querySelector('#nav-categories').innerHTML=categoryLinks();document.querySelector('#cart-count').textContent=cart.reduce((n,x)=>n+x.qty,0);document.querySelector('#account-link').textContent=logged?t("ACCOUNT"):t("LOGIN");document.querySelector('#account-link').href=logged?'#account':'#login'}
function card(p){return `<a class="product" href="#product/${p.id}"><div class="image"><img src="${p.img}" alt="${esc(productName(p))}" loading="lazy">${p.id%4===1?t('<span class="badge">NEW ARRIVAL</span>'):''}</div><p>${esc(productName(p))}</p><strong>${money(p.price)}</strong></a>`}
const categoryLinks=(active='ALL')=>cats.map(c=>`<a class="${c===active?'active':''}" href="#shop/${c}">${t(c)}</a>`).join('');
document.querySelector('#nav-categories').innerHTML=categoryLinks();
function route(){delete app.dataset.completion;delete app.dataset.reply;const [page='home',arg,pg]=location.hash.slice(1).split('/');updateHeader();document.title='DOA — '+page.toUpperCase();if(page==='home')home();else if(page==='shop')shop(arg||'ALL',Number(pg)||1);else if(page==='product')detail(Number(arg));else if(page==='cart')cartPage();else if(page==='login')login();else if(page==='signup')signup();else if(page==='account')account();else if(page==='checkout')checkout();else if(page==='community')community();else if(page==='post')post(Number(arg));else if(page==='write')write(arg);else if(page==='about')about();else if(page==='find')find(arg);else home();window.scrollTo(0,0)}
function home(){app.innerHTML=`<section class="hero"><div class="hero-copy"><div class="eyebrow">DOA / 2026 NEW SEASON</div><h1>A door to<br>your taste.</h1><p>${t("하나의 옷에서 시작되는 새로운 감각.")}<br>${t("당신만의 취향이 열리는 곳, DOA.")}</p><a class="primary" href="#shop">${t("EXPLORE COLLECTION ↗")}</a></div><div class="hero-art"><img src="assets/outer-0.svg" alt="${t("DOA 스트럭처드 재킷 컬렉션")}"><span class="art-label">01 — EVERYDAY, IN YOUR OWN WAY.</span></div></section><section class="section"><div class="row section-title"><div><div class="eyebrow">THE ${t("EDIT")}</div><h2>${t("New arrivals")}</h2></div><a href="#shop">${t("VIEW ALL ↗")}</a></div><div class="grid">${[products[0],products[102],products[200],products[400]].map(card).join('')}</div></section><section class="community-band"><div><div class="eyebrow">OUR ${t("COMMUNITY")} / YOUR PERSPECTIVE</div><h2>Different tastes.<br>One open door.</h2><p class="muted">${t("나의 아웃핏이 누군가의 새로운 영감이 되도록.")}</p></div><a class="secondary" href="#community">${t("EXPLORE OUTFITS ↗")}</a></section>`}
function shop(cat,page){if(!cats.includes(cat))cat='ALL';page=Math.max(1,Math.min(5,page));let list=products.filter(p=>(cat==='ALL'||p.cat===cat)&&(!searchQuery||(p.name+" "+productName(p)).toLowerCase().includes(searchQuery.toLowerCase())));app.innerHTML=`<section class="section"><div class="row section-title"><div><div class="eyebrow">${t("SHOP")} / ${t(cat)}</div><h1>${searchQuery?t("Search results"):cat==='ALL'?t("All pieces"):t(cat)}</h1></div><p class="muted">${t("새로운 취향을 발견하는 일.")}</p></div><div class="category-bar">${categoryLinks(cat)}</div>${searchQuery?`<p>“${esc(searchQuery)}${t("” 검색 결과 ")}<button id="clear-search">${t("✕ 검색 해제")}</button></p>`:''}<div class="toolbar"><span class="muted">${list.length} ITEMS</span><select id="sort" aria-label="${t("상품 정렬")}"><option value="new">${t("NEW ARRIVALS")}</option><option value="low">${t("PRICE: LOW TO HIGH")}</option><option value="high">${t("PRICE: HIGH TO LOW")}</option></select></div><div class="grid" id="products"></div><div class="pages"><a href="#shop/${cat}/${Math.max(1,page-1)}">${t("PREV")}</a>${[1,2,3,4,5].map(n=>`<a class="${page===n?'active':''}" href="#shop/${cat}/${n}">${n}</a>`).join('')}<a href="#shop/${cat}/${Math.min(5,page+1)}">${t("NEXT")}</a></div></section>`;const paint=()=>{const value=document.querySelector('#sort').value;const sorted=[...list];if(value!=='new')sorted.sort((a,b)=>value==='low'?a.price-b.price:b.price-a.price);document.querySelector('#products').innerHTML=sorted.slice((page-1)*20,page*20).map(card).join('')||t("<p class=\"muted\">이 페이지에 상품이 없습니다.</p>")};paint();document.querySelector('#sort').onchange=paint;const clear=document.querySelector('#clear-search');if(clear)clear.onclick=()=>{searchQuery='';shop(cat,1)}}
function detail(id){const p=products.find(x=>x.id===id);if(!p){app.innerHTML=t("<section class=\"empty\">상품을 찾을 수 없습니다. <a href=\"#shop\">SHOP</a></section>");return}app.innerHTML=`<section class="detail"><img src="${p.img}" alt="${esc(productName(p))}"><div><div class="eyebrow">${t("SHOP")} / ${t(p.cat)}</div><h1>${esc(productName(p))}</h1><p class="price">${money(p.price)}</p><p class="muted">${t("절제된 디테일과 자연스러운 실루엣.")}<br>${t("당신의 일상에 오래 머무를 한 조각.")}</p><form id="options"><label>${t("COLOR")}<select name="color" required><option value="">${t("색상을 선택하세요")}</option><option value="CHARCOAL">${t("CHARCOAL")}</option><option value="IVORY">${t("IVORY")}</option><option value="STONE">${t("STONE")}</option></select></label><label>${t("SIZE")}<select name="size" required><option value="">${t("사이즈를 선택하세요")}</option><option value="OS (ONE SIZE)">${t("OS (ONE SIZE)")}</option><option>S</option><option>M</option><option>L</option></select></label><div class="actions"><button class="secondary" name="action" value="cart">${t("ADD TO CART")}</button><button class="primary" name="action" value="buy">${t("BUY NOW")}</button></div></form><details open><summary>${t("SIZE & DETAILS")}</summary><p class="muted">${t("SIZE (CM) · 총장 72 / 어깨 50.5 / 가슴 49 / 소매 66")}<br>MADE IN KOREA<br>MODEL · 170cm / 44–55 size<br>${t("측정 방식에 따라 1–3cm 차이가 있을 수 있습니다.")}<br>${t("치수 및 상품 정보는 UI 시연용입니다.")}</p></details><details><summary>${t("DELIVERY & RETURNS")}</summary><p>${t("배송비 3,000원 · 100,000원 이상 무료배송")}<br>${t("배송 및 교환 정책은 시연용 안내입니다.")}</p></details></div></section>`;document.querySelector('#options').onsubmit=e=>{e.preventDefault();const d=new FormData(e.target),color=d.get('color'),size=d.get('size');const x=cart.find(x=>x.id===id&&x.color===color&&x.size===size);if(x)x.qty++;else cart.push({id,color,size,qty:1});save();if(e.submitter.value==='buy')location.hash='checkout';else toast(t("장바구니에 담았습니다."))}}
function cartPage(){app.innerHTML=`<section class="section"><div class="section-title"><div class="eyebrow">${t("YOUR SELECTION")}</div><h1>${t("Shopping bag")}</h1></div>${!cart.length?t("<div class=\"empty\"><p>장바구니가 비어 있습니다.</p><a class=\"primary\" href=\"#shop\">쇼핑하러 가기</a></div>"):cart.map((x,i)=>{const p=products.find(p=>p.id===x.id);return `<div class="cart-item"><a href="#product/${p.id}"><img src="${p.img}" alt="${esc(productName(p))}"></a><div><a href="#product/${p.id}">${esc(productName(p))}</a><p class="muted">${esc(t(x.color))} / ${esc(t(x.size))}</p><div class="quantity"><button data-qty="${i}" data-delta="-1" aria-label="${t("수량 감소")}">−</button>${x.qty}<button data-qty="${i}" data-delta="1" aria-label="${t("수량 증가")}">+</button><button data-remove="${i}" aria-label="${t("상품 삭제")}">✕</button></div></div><div>${money(p.price*x.qty)}</div></div>`}).join('')+totals()+'</section>'}`;app.querySelectorAll('[data-qty]').forEach(b=>b.onclick=()=>{const x=cart[Number(b.dataset.qty)];x.qty=Math.max(1,x.qty+Number(b.dataset.delta));save();cartPage()});app.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{cart.splice(Number(b.dataset.remove),1);save();cartPage()})}
const subtotal=()=>cart.reduce((n,x)=>n+products.find(p=>p.id===x.id).price*x.qty,0),shipping=()=>subtotal()>=100000||!cart.length?0:3000;
function totals(){return `<div class="total"><div class="row"><span>${t("상품 금액")}</span><span>${money(subtotal())}</span></div><div class="row"><span>${t("배송비")}</span><span>${money(shipping())}</span></div><div class="row"><strong>${t("TOTAL")}</strong><strong>${money(subtotal()+shipping())}</strong></div><a class="primary" href="#checkout">${t("주문하기")}</a></div>`}
function login(){if(logged){location.hash='account';return}app.innerHTML=`<section class="form-page"><div class="eyebrow">${t("WELCOME BACK")}</div><h1>${t("LOGIN")}</h1><form id="login-form"><label>${t("아이디")}<input name="id" autocomplete="username" required></label><label>${t("비밀번호")}<input name="password" type="password" autocomplete="current-password" required></label><p class="error" id="login-error"></p><button class="primary">${t("로그인")}</button></form><a class="secondary" href="#signup">${t("회원가입")}</a><div class="form-links"><a href="#find/id">${t("아이디 찾기")}</a><a href="#find/password">${t("비밀번호 찾기")}</a></div><p class="muted">${t("UI 체험은 demo / demo1234로 로그인하세요.")}<br>${t("회원가입 정보는 이 브라우저에서만 사용됩니다.")}</p></section>`;document.querySelector('#login-form').onsubmit=e=>{e.preventDefault();const d=new FormData(e.target);if((d.get('id')==='demo'&&d.get('password')==='demo1234')||(profile&&profile.id===d.get('id')&&window.demoPassword===d.get('password'))){logged=true;location.hash='account'}else document.querySelector('#login-error').textContent=t("아이디 또는 비밀번호를 확인하세요. 새로고침 후에는 demo 계정을 사용하세요.")}}
function signup(){app.innerHTML=`<section class="form-page"><div class="eyebrow">${t("OPEN YOUR DOOR")}</div><h1>${t("JOIN DOA")}</h1><p class="muted">${t("시연용 회원가입입니다. 실제 개인정보 대신 예시 정보를 사용하세요.")}</p><form id="signup-form">${[['id',t("아이디"),'text'],['password',t("비밀번호 (8자 이상)"),'password'],['confirm',t("비밀번호 확인"),'password'],['name',t("이름"),'text'],['phone',t("휴대폰 번호"),'tel'],['email',t("이메일"),'email'],['address',t("주소"),'text']].map(([name,label,type])=>`<label>${label}<input name="${name}" type="${type}" ${type==='password'?'minlength="8"':''} required></label>`).join('')}<p class="error" id="join-error"></p><button class="primary">${t("회원가입")}</button></form></section>`;document.querySelector('#signup-form').onsubmit=e=>{e.preventDefault();const d=new FormData(e.target);if(d.get('password')!==d.get('confirm')){document.querySelector('#join-error').textContent=t("비밀번호가 일치하지 않습니다.");return}profile={id:d.get('id'),name:d.get('name'),email:d.get('email')};window.demoPassword=d.get('password');logged=true;save();renderSignupComplete()}}
function account(){if(!logged){location.hash='login';return}app.innerHTML=`<section class="section"><div class="section-title"><div class="eyebrow">${t("MY DOA")}</div><h1>${esc(profile?.name||'DOA MEMBER')}${t("님, 안녕하세요.")}</h1></div><div class="category-bar"><a href="#account/orders">${t("주문조회")}</a><a href="#account/info">${t("회원정보")}</a><a href="#cart">${t("장바구니")}</a><a href="#account/posts">${t("게시물 관리")}</a><button id="logout">${t("로그아웃")}</button></div><h2>${t("회원정보")}</h2><p>${t("아이디 · ")}${esc(profile?.id||'demo')}<br>${t("이메일 · ")}${esc(profile?.email||'demo@example.com')}</p><h2>${t("주문조회")}</h2>${orders.length?orders.map(o=>`<p>${esc(o.id)} · ${money(o.total)}${t(" · 시연 완료")}</p>`).join(''):t("<p class=\"muted\">주문 내역이 없습니다.</p>")}<h2>${t("내 게시물")}</h2>${posts.filter(p=>p.mine).map(p=>`<p><a href="#post/${p.id}">${esc(postTitle(p))} ↗</a></p>`).join('')||t("<p class=\"muted\">작성한 게시물이 없습니다.</p>")}</section>`;document.querySelector('#logout').onclick=()=>{logged=false;location.hash='home';toast(t("로그아웃되었습니다."))}}
function find(type){app.innerHTML=`<section class="form-page"><h1>${type==='id'?t("아이디 찾기"):t("비밀번호 찾기")}</h1><p>${t("시연용 화면입니다. 실제 이메일은 발송되지 않습니다.")}</p><form id="find-form"><label>${t("이메일")}<input name="email" type="email" required></label><button class="primary">${t("확인")}</button></form><p id="find-result"></p><a href="#login">${t("로그인으로 돌아가기")}</a></section>`;document.querySelector('#find-form').onsubmit=e=>{e.preventDefault();const email=new FormData(e.target).get('email');document.querySelector('#find-result').textContent=profile?.email===email?(type==='id'?t("가입 아이디: ")+profile.id:t("시연 계정은 demo / demo1234로 로그인할 수 있습니다.")):t("해당 이메일의 시연 계정이 없습니다.")}}
function checkout(){if(!cart.length){location.hash='cart';return}app.innerHTML=`<section class="form-page"><div class="eyebrow">${t("CHECKOUT")}</div><h1>${t("주문서")}</h1><p class="muted">${t("결제 UI 시연입니다. 실제 정보 입력 및 결제는 필요하지 않습니다.")}</p><form id="checkout-form"><label>${t("받는 사람")}<input required name="name"></label><label>${t("배송지")}<input required name="address"></label><label>${t("전화번호")}<input required type="tel"></label><label>${t("이메일")}<input required type="email"></label><label>${t("결제 방법")}<select required><option>${t("신용카드 (시연)")}</option><option>${t("무통장 입금 (시연)")}</option></select></label><p>${t("총 금액 ")}${money(subtotal()+shipping())}</p><button class="primary">${t("결제 화면 시연 완료")}</button></form></section>`;document.querySelector('#checkout-form').onsubmit=e=>{e.preventDefault();const total=subtotal()+shipping();orders.push({id:'DOA-'+Date.now(),total});cart=[];save();renderCheckoutComplete()}}
function community(){let list=[...posts].sort((a,b)=>communitySort==='popular'?b.likes-a.likes:b.id-a.id);app.innerHTML=`<section class="section"><div class="row section-title"><div><div class="eyebrow">STYLE CONNECTS US</div><h1>${t("Our outfits")}</h1><p class="muted">${t("다른 감각, 새로운 발견. 당신의 오늘을 공유하세요.")}</p></div><a class="secondary" href="#write">${t("SHARE YOUR OUTFIT ↗")}</a></div><div class="toolbar"><span>${t("COMMUNITY / OUTFIT")}</span><select id="post-sort"><option value="latest">${t("최신순")}</option><option value="popular">${t("인기순")}</option></select></div><div class="outfits">${list.map(p=>`<article class="outfit"><a href="#post/${p.id}"><div class="visual"><img src="${esc(p.image)}" alt="${esc(postTitle(p))}"></div><p class="eyebrow">${esc(p.author)}</p><h3>${esc(postTitle(p))}</h3></a><button class="like" data-like="${p.id}">${p.liked?'♥':'♡'} ${p.likes}</button></article>`).join('')}</div></section>`;document.querySelector('#post-sort').value=communitySort;document.querySelector('#post-sort').onchange=e=>{communitySort=e.target.value;community()};bindLikes()}
function toggleLike(id){const p=posts.find(x=>x.id===id);p.liked=!p.liked;p.likes+=p.liked?1:-1;save()}
function bindLikes(){app.querySelectorAll('[data-like]').forEach(b=>b.onclick=()=>{toggleLike(Number(b.dataset.like));b.textContent=(posts.find(p=>p.id===Number(b.dataset.like)).liked?'♥':'♡')+' '+posts.find(p=>p.id===Number(b.dataset.like)).likes})}
function post(id){delete app.dataset.reply;const p=posts.find(x=>x.id===id);if(!p){location.hash='community';return}app.innerHTML=`<section class="section post-view"><a href="#community">${t("← ALL OUTFITS")}</a><h1>${esc(postTitle(p))}</h1><p class="eyebrow">${esc(p.author)}</p><img src="${esc(p.image)}" alt="${esc(postTitle(p))}"><p>${esc(postText(p))}</p><button class="like" data-like="${p.id}">${p.liked?'♥':'♡'} ${p.likes}</button>${p.mine?` <a class="secondary" href="#write/${id}">${t("수정")}</a> <button class="secondary" id="delete-post">${t("삭제")}</button>`:''}<h3>${t("WORN IN THIS OUTFIT")}</h3>${p.tags.map(id=>`<button class="tag" data-tag="${id}">${esc(productName(products.find(x=>x.id===id))||t("상품"))}</button>`).join('')}<div id="tag-info"></div><h3>${t("COMMENTS")}</h3><div id="comments">${p.comments.map((c,i)=>`<div class="comment"><strong>${esc(c.author)}</strong><p>${esc(c.text)}</p><button data-reply="${i}">${t("답글 달기")}</button>${(c.replies||[]).map(r=>`<p class="reply">↳ ${esc(r)}</p>`).join('')}</div>`).join('')}</div><form id="comment-form"><label id="comment-label">${t("댓글 작성")}<input name="text" maxlength="500" required placeholder="${t("당신의 생각을 나눠주세요")}"></label><button class="primary">${t("등록")}</button><button type="button" id="cancel-reply" hidden>${t("답글 취소")}</button></form></section>`;bindLikes();let reply=null;app.querySelectorAll('[data-tag]').forEach(b=>b.onclick=()=>{const x=products.find(p=>p.id===Number(b.dataset.tag));document.querySelector('#tag-info').innerHTML=`<div class="tag-info"><strong>${esc(productName(x))}</strong><p>${money(x.price)}</p><a class="primary" href="#product/${x.id}">${t("상품 상세보기 ↗")}</a></div>`});app.querySelectorAll('[data-reply]').forEach(b=>b.onclick=()=>{reply=Number(b.dataset.reply);app.dataset.reply=String(reply);document.querySelector('#comment-label').firstChild.textContent=t("답글 작성");document.querySelector('#cancel-reply').hidden=false;document.querySelector('#comment-form input').focus()});document.querySelector('#cancel-reply').onclick=()=>{reply=null;delete app.dataset.reply;document.querySelector('#comment-label').firstChild.textContent=t("댓글 작성");document.querySelector('#cancel-reply').hidden=true};document.querySelector('#comment-form').onsubmit=e=>{e.preventDefault();const text=new FormData(e.target).get('text').trim();if(!text)return;if(reply!==null){p.comments[reply].replies??=[];p.comments[reply].replies.push(text)}else p.comments.push({author:profile?.name||'GUEST',text,replies:[]});save();post(id);toast(t("댓글이 등록되었습니다."))};if(p.mine)document.querySelector('#delete-post').onclick=()=>{if(confirm(t("게시물을 삭제할까요?"))){posts=posts.filter(x=>x.id!==id);save();location.hash='community'}}}
function write(id){if(!logged){toast(t("로그인 후 아웃핏을 공유할 수 있습니다."));location.hash='login';return}const p=posts.find(x=>x.id===Number(id));if(p&&!p.mine){location.hash='community';return}app.innerHTML=`<section class="form-page"><h1>${p?t("EDIT"):t("SHARE")}${t(" YOUR OUTFIT")}</h1><form id="write-form"><label>${t("제목")}<input name="title" maxlength="100" required value="${esc(p?.title||'')}"></label><label>${t("이미지 업로드")}<input name="image" type="file" accept="image/png,image/jpeg,image/webp"></label><p class="muted">${t("최대 2MB. 업로드하지 않으면 DOA 일러스트가 사용됩니다.")}</p><label>${t("오늘의 이야기")}<textarea name="text" required maxlength="2000">${esc(p?.text||'')}</textarea></label><label>${t("상품 태그 (여러 개 선택 가능)")}<select name="tags" multiple size="6">${[products[0],products[100],products[102],products[200],products[300],products[400],products[500]].map(x=>`<option value="${x.id}" ${p?.tags.includes(x.id)?'selected':''}>${esc(productName(x))}</option>`).join('')}</select></label><button class="primary">${t("게시물 ")}${p?t("수정"):t("등록")}</button></form></section>`;document.querySelector('#write-form').onsubmit=async e=>{e.preventDefault();const d=new FormData(e.target),f=d.get('image');if(f.size>2*1024*1024){toast(t("2MB 이하 이미지를 선택하세요."));return}if(f.size&&!['image/png','image/jpeg','image/webp'].includes(f.type)){toast(t("PNG, JPEG, WEBP 이미지를 선택하세요."));return}const image=f.size?await new Promise((resolve,reject)=>{const r=new FileReader;r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(f)}):p?.image||'assets/outer-0.svg';const item={id:p?.id||Date.now(),title:d.get('title'),text:d.get('text'),author:profile?.name||'DOA MEMBER',image,tags:d.getAll('tags').map(Number),mine:true,likes:p?.likes||0,comments:p?.comments||[]};if(p)posts[posts.indexOf(p)]=item;else posts.push(item);save();location.hash='post/'+item.id}}
function about(){app.innerHTML=`<section class="section about"><div class="eyebrow">DOA / ドア / DOOR</div><h1>A door to your taste.</h1><p>${t("DOA는 새로운 취향과 감각을 발견하는 ‘문’을 의미합니다. 하나의 옷에서 시작된 개인의 취향이 새로운 스타일과 사람을 만나 더 넓은 세계로 이어지는 시작점이 되고자 합니다.")}</p><p>${t("옷은 자신의 취향을 표현하는 매개체입니다. 정해진 답 대신, 각자의 감각을 발견하고 자유롭게 표현하는 공간. 패션에서 시작된 작은 취향이 사람과 사람을 연결하고 하나의 문화로 이어집니다.")}</p><a class="primary" href="#community">${t("우리의 커뮤니티 만나기")}</a><h2>${t("CUSTOMER SERVICE")}</h2><p>${t("배송 · 교환 · 반품 안내는 상품 상세에서 확인할 수 있습니다.")}<br>${t("이 사이트는 개발 초안을 바탕으로 제작한 UI 프로토타입입니다.")}</p></section>`}
document.querySelector('#search-open').onclick=()=>document.querySelector('#search').showModal();document.querySelector('#search-close').onclick=()=>document.querySelector('#search').close();document.querySelector('#search-form').onsubmit=e=>{e.preventDefault();searchQuery=new FormData(e.target).get('query').trim();document.querySelector('#search').close();if(location.hash==='#shop/ALL/1')shop('ALL',1);else location.hash='shop/ALL/1'};window.addEventListener('hashchange',route);route();

function renderSignupComplete(){app.dataset.completion="signup";app.innerHTML=`<section class="form-page"><div class="eyebrow">${t("WELCOME TO DOA")}</div><h1>${t("새로운 문이 열렸습니다.")}</h1><p>${t("회원가입이 완료되었습니다.")}</p><p>${t("아이디 · ")}${esc(profile.id)}<br>${t("이름 · ")}${esc(profile.name)}<br>${t("이메일 · ")}${esc(profile.email)}</p><a class="primary" href="#home">${t("쇼핑하기")}</a></section>`;updateHeader();}

function renderCheckoutComplete(){app.dataset.completion="checkout";app.innerHTML=t("<section class=\"empty\"><h1>주문 UI 시연이 완료되었습니다.</h1><p>실제 결제 및 주문 접수는 이루어지지 않았습니다.</p><a class=\"primary\" href=\"#home\">홈으로 돌아가기</a></section>");updateHeader();}

// Re-render fixed copy while retaining inputs, options and uploaded files.
document.querySelector('#language').addEventListener('change',event=>{
  const next=event.target.value;if(!['ko','ja'].includes(next)||next===language)return;
  const controls=[...app.querySelectorAll('input,textarea,select')].map(el=>({el,value:el.value,selected:el.tagName==='SELECT'?[...el.options].filter(o=>o.selected).map(o=>o.value):null}));
  const completion=app.dataset.completion,reply=app.dataset.reply;
  const tagged=app.querySelector('#tag-info a')?.getAttribute('href');
  const position=window.scrollY;
  language=next;try{localStorage.setItem('doa-language',language)}catch{}
  if(completion==='signup')renderSignupComplete();else if(completion==='checkout')renderCheckoutComplete();else route();
  const fresh=[...app.querySelectorAll('input,textarea,select')];
  controls.forEach((old,i)=>{const el=fresh[i];if(!el)return;if(old.el.type==='file'){el.replaceWith(old.el);return;}el.value=old.value;if(old.selected)[...el.options].forEach(o=>o.selected=old.selected.includes(o.value));});
  if(reply!==undefined)app.querySelector(`[data-reply="${reply}"]`)?.click();
  if(tagged)app.querySelector(`[data-tag="${tagged.split('/').pop()}"]`)?.click();
  if(app.querySelector('#sort'))app.querySelector('#sort').dispatchEvent(new Event('change'));
  document.querySelector('#toast').style.display='none';
  window.scrollTo(0,position);
});
